services:
    website:
        image: 'ghcr.io/discordlookup/discordlookup:main'
        restart: unless-stopped
        environment:
            APP_NAME: DiscordLookup
            APP_ENV: local
            APP_KEY: ''
            APP_DEBUG: 'true'
            APP_URL: http://localhost
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: discordlookup
            DB_USERNAME: discordlookup
            DB_PASSWORD: discordlookup
            REDIS_HOST: dragonfly
            REDIS_PORT: 6379
            REDIS_PASSWORD: dragonfly
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            SENTRY_LARAVEL_DSN: ''
            SENTRY_TRACES_SAMPLE_RATE: 1.0
            DISCORD_CLIENT_ID: 892399371910524938
            DISCORD_CLIENT_SECRET: ''
            DISCORD_BOT_TOKEN: ''
            DISCORD_REDIRECT_URI: http://localhost/auth/callback
            DISCORD_GUILD_ID: 980791496833908778
            DISCORD_EXPERIMENTS_WORKER: https://experiments.workers.discordlookup.com
            INVITE_URL: https://discord.com/oauth2/authorize?client_id=892399371910524938&permissions=275951963136&scope=bot%20applications.commands
            PLAUSIBLE_URL: ''
            PLAUSIBLE_WEBSITE_DOMAIN: ''
            LEGAL_FIRSTNAME: ''
            LEGAL_LASTNAME: ''
            LEGAL_ADDRESS: ''
            LEGAL_ADDRESS_ADDITIONAL: ''
            LEGAL_ZIPCODE: ''
            LEGAL_CITY: ''
            LEGAL_COUNTRY: ''
            LEGAL_PHONE: ''
            LEGAL_EMAIL: ''
        ports:
            - 127.0.0.1:8080:8080
        networks:
            - discordlookup
        depends_on:
            - mysql
            - dragonfly
    mysql:
        image: mariadb:10.11
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: discordlookup
            MYSQL_DATABASE: discordlookup
            MYSQL_USER: discordlookup
            MYSQL_PASSWORD: discordlookup
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - discordlookup
    dragonfly:
        image: ghcr.io/dragonflydb/dragonfly:v1.25.4
        restart: unless-stopped
        ulimits:
            memlock: -1
        environment:
            DFLY_requirepass: dragonfly
        volumes:
            - dragonfly:/data
        networks:
            - discordlookup

volumes:
    mysql:
    dragonfly:

networks:
    discordlookup:
        driver: bridge
